### PR TITLE
Add event to update back the original select element

### PR DESCRIPTION
**Pull request by rulrok**

### CODE REVIEW

**Comment by Palmr** [comment]
Hey, thanks for raising this issue and for sending us a fix too.

If you could add in an example (probably another tagger and a couple of JS buttons to change the underlying selection?) to examples/examples.htm that would be helpful for us to test with. If not let me know and I'll merge this request and add an example myself later.

**Comment by rulrok** [comment]
Recently, I am not able to do it.
I would appreciate it if you have the time for so :)

**Comment by rulrok** [comment]
I made the change only for single selects. I don't know if that is the same thing for multiple `selects`.
Only because I really needed that on my project working, I've changed only for single `selects`.

If you think it is simple for multiples, we could tackle this down already.

**Comment by Palmr** [comment]
That's okay, I'll merge your changes now and I can add support for multi-selects and add examples later.

**Pull request merged**
